title: Kurtuluş Buluş
email: kurtulusbulus at gmail dot com
description: >-
  Postdoctoral researcher working on SPAD imaging, biomedical optics,
  time-resolved Raman spectroscopy and computational imaging.

baseurl: ""
url: "https://kurtulusbulus.github.io/"
linkedin_username: kurtulusbulus01
github_username: kurtulusbulus

header_pages:
  - research.markdown
  - projects.markdown
  - publications.markdown
  - about.markdown
  - blog.markdown

theme: minima
plugins:
  - jekyll-feed
